/**
 * FeedbackReplies component.
 *
 * Renders the reply thread under an AI Feedback note — existing user and
 * AI replies plus, when a reply is being generated, a pending indicator
 * that polls /replies/{id}/status for completion.
 */
import { __ } from '@wordpress/i18n';
import { Spinner } from '@wordpress/components';
import useReplyStatus from '../hooks/useReplyStatus';

/**
 * @typedef {Object} Reply
 * @property {number|string} id      Comment ID.
 * @property {string}        author  Author name.
 * @property {string}        content Reply body. Plain text — rendered as a text node, never HTML.
 * @property {boolean}       is_ai   Whether this reply was generated by AI Feedback.
 */

/**
 * @param {Object}      props
 * @param {Reply[]}     props.replies          Existing replies in the thread, chronological.
 * @param {number|null} [props.pendingReplyId] Optional user-reply comment ID whose AI response
 *                                             is being generated. Triggers polling + pending row.
 * @return {Element|null} The reply thread, or `null` when there are no replies and nothing pending.
 */
export default function FeedbackReplies({
	replies = [],
	pendingReplyId = null,
}) {
	const { status } = useReplyStatus(pendingReplyId);
	const hasPendingSlot = Boolean(pendingReplyId);
	const isPolling =
		hasPendingSlot && status !== 'complete' && status !== 'failed';

	if (replies.length === 0 && !hasPendingSlot) {
		return null;
	}

	return (
		<ul
			className="ai-feedback-replies"
			aria-label={__('Conversation replies', 'ai-feedback')}
		>
			{replies.map((reply) => (
				<li
					key={reply.id}
					className={
						'ai-feedback-reply' +
						(reply.is_ai
							? ' ai-feedback-reply-ai'
							: ' ai-feedback-reply-user')
					}
				>
					<span className="ai-feedback-reply-author">
						{reply.is_ai
							? __('AI Feedback', 'ai-feedback')
							: reply.author}
					</span>
					<span className="ai-feedback-reply-content">
						{reply.content}
					</span>
				</li>
			))}

			{/*
			 * The aria-live region must already be in the DOM before its
			 * content changes for NVDA / JAWS to announce reliably. Render
			 * the <li> for the entire pending lifecycle (any time
			 * pendingReplyId is set) and toggle the spinner content based
			 * on whether we are still polling.
			 */}
			{hasPendingSlot && (
				<li
					className="ai-feedback-reply ai-feedback-reply-pending"
					aria-live="polite"
					aria-atomic="true"
				>
					{isPolling && (
						<>
							<Spinner />
							<span className="ai-feedback-reply-content">
								{__('AI is replying…', 'ai-feedback')}
							</span>
						</>
					)}
				</li>
			)}
		</ul>
	);
}
